export const DOCUMENT_INSERTED_EVENT = 'DOCUMENT_INSERTED';
export const DOCUMENT_UPDATED_EVENT = 'DOCUMENT_UPDATED';
export const DOCUMENT_DELETED_EVENT = 'DOCUMENT_DELETED';
export const DB_CHANGE_EVENT = 'DB_CHANGE_EVENT';



