import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  logger: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the root of the docs folder
    },
  ]
};

export default sidebars;



// module.exports = {
//   logger: [
//     'intro',
//     'getting-started',
//     // {
//     //   type: 'category',
//     //   label: 'Guides',
//     //   items: ['configuration', 'usage', 'advanced-logging'],
//     // },
//   ],
// };
