import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

type SidebarItemDoc = {
  type: 'doc';
  id: string;
  label: string;
  customProps: Record<string, unknown>;
}

const sidebars: SidebarsConfig = {
  core: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the root of the docs folder
    },
  ]
};


export default sidebars;






// module.exports = {
//   core: [
//     'intro',
//     'getting-started',
//     {
//       type: 'category',
//       label: 'Guides',
// 			items: [
// 				'schemas',
// 				'models',
// 				'relations',
// 				'graphql',
// 				'gc',
// 				'rbac',
// 				'caching',
// 				'redis',
// 			],
//     },
//   ],
// };
