import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
	adapter: [
		 {
      type: 'autogenerated',
      dirName: '.', // '.' means the root of the docs folder
    }
		// 'intro',
		// {
		// 	type: 'category',
		// 	label: 'Adapters',
		// 	items: [
		// 		'/intro',
		// 		'/overview', 
		// 		'/trouble-shooting',
		// 	],
		// } 
	]
};

export default sidebars;

// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


// const sidebars: SidebarsConfig = {
//   adapters: [
//     {
//       type: 'autogenerated',
//       dirName: '.', // '.' means the root of the docs folder
//     },

//   ]
// };

// export default sidebars;
