import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  cli: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the root of the docs folder
    },

  ]
};

export default sidebars;




// module.exports = {
//   cli: [
//     'intro',
//     'getting-started',
//     {
//       type: 'category',
//       label: 'Guides',
//       items: ['commands', 'configuration', 'advanced-usage'],
//     },
//   ],
// };
