/**
 * @author Emmanuel Nodolomwanyi - Abimongo Team
 * @package - @abimongo/core
 * @version 1.1.5
 */

/**
 * Abimongo Core Library
 * This library provides core functionalities for Abimongo, ORM/ODM solution
 * for MongoDB in Node.js and Browser environments.
 * @module Abimongo Core Library
 * @version 1.1.5
 */


// Do not edit this file
import { AbimongoClient } from './lib-core/AbimongoClient.js';
import { RedisService } from './redis-manager/redisClient.js';

console.log('Abimongo Core Library Loaded. \n (Node.js environment detected.)');

export const initializeRedis = async (
	{ useRedis = false }: { useRedis?: boolean } = {}
) => {
	// Initialize Redis connection if useRedis is true
	if (!useRedis) {
		const redisClient = RedisService.getInstance();
		(await redisClient.getClient()).connect()
	}
};

declare global {
	interface Window {
		abimongoClient: typeof 	AbimongoClient;
	}
}


if (typeof window !== 'undefined') {
	window.abimongoClient = AbimongoClient;
	window.Buffer = Buffer;
}

export * from './lib-core/index.js';
export * from './lib-core/bootstrap/index.js';
export * from './config/index.js';
export * from './redis-manager/redisClient.js';
export * from './tanancy/index.js';
export * from './context/index.js';
export * from './plugins/index.js';
export * from './instrumentation/index.js';
export * from './debug/index.js';

// This export is needed for adapter-types to avoid circular dependency issues
// when both packages are used together.
// export { runWithAdapterContext, resolveTenant } from "@abimongo/adapter-types";

export * from './init-cli/generate.project.js';
export * from './middleware/index.js';
export * from './graphql/index.js';
export * from './utils/index.js';
export * from './utils/builders/index.js';
export * from './gc/AbimongoGC.js';
export * from './utils/error/index.js';
export * from './utils/color-palatte.js';
export { GCSettings } from './decorators/gcSettings.js';
export * from './types/index.js';
export type { SchemaType } from './types/schema.type.js';
export type { Document } from './types/document.js';
export type { ErrorType } from './utils/error/errorTypes.js';