/**
 * @author Emmanuel Nodolomwanyi - Abimongo Team
 */

/**
 * Abimongo Core Library for
 * This module provides core functionalities for Abimongo in a browser environment.
 * It includes database operations, configuration, and more.
 * @module Abimongo Core Module
 */

// Do not edit this file
import { AbimongoClient } from './lib-core/AbimongoClient';
import { RedisService } from './redis-manager/redisClient';

export const initializeRedis = async (
	{ useRedis = false }: { useRedis?: boolean } = {}
) => {
	// Initialize Redis connection if useRedis is true
	if (!useRedis) {
		const redisClient = RedisService.getInstance();
		(await redisClient.getClient()).connect()
	}
};

declare global {
	interface Window {
		abimongoClient: typeof AbimongoClient;
	}
}


if (typeof window !== 'undefined') {
	window.abimongoClient = AbimongoClient;
	window.Buffer = Buffer;
}

export * from './lib-core';
export * from './lib-core/bootstrap';
export * from './config';
export * from './redis-manager/redisClient';
export * from './tanancy';
export { applyMultiTenancy } from './tanancy/applyMultiTenancy';
export * from './init-cli/generate.project';
export * from './middleware'
export * from './graphql';
export * from './utils/index';
export * from './utils/builders'
export * from './gc/AbimongoGC';
export * from './utils/error';
export { GCSettings } from './decorators/gcSettings';
export * from './types';
export { SchemaType } from './types/schema.type';
export type { Document } from './types/document';
export type { ErrorType } from './utils/error/errorTypes';