// Do not edit this file
import { AbimongoClient } from './lib-core/AbimongoClient';
import { RedisService } from './redis-manager/redisClient';
import { program } from '../bin/abimongo-core-cli'


/**
 * Abimongo Core Library
 * This library provides core functionalities for Abimongo, including database operations, configuration, and more.
 * It is designed to be used both in Node.js and browser environments.
 * @module AbimongoCore
 * @version 1.0.0
 */

export const initializeRedis = async (
	{ useRedis = false }: { useRedis?: boolean } = {}
) => {
	// Initialize Redis connection if useRedis is true
	if (!useRedis) {
		const redisClient = RedisService.getInstance();
		(await redisClient.getClient()).connect()
	}
};

declare global {
	interface Window {
		abimongoClient: typeof AbimongoClient;
	}
}


if (typeof window !== 'undefined') {
	window.abimongoClient = AbimongoClient;
	window.Buffer = Buffer;
}

console.log('Abimongo Core Library Loaded');

export * from '../bin/abimongo-core-cli'


export * from './lib-core';
export * from './lib-core/bootstrap';
export * from './config';
export * from './redis-manager/redisClient';
export * from './tanancy';
export { applyMultiTenancy } from './tanancy/applyMultiTenancy';
export * from './init-cli/generate.project';
export * from './middleware'
export * from './graphql';
export * from './utils/index';
export * from './utils/builders'
export * from './gc/AbimongoGC';
export * from './utils/error';
// export * from './config/setupLogger';
export { GCSettings } from './decorators/gcSettings';
// export { normalizeLoggerConfig } from './loggers/normalizeLoggerConfig';
export * from './types';
export { SchemaType } from './types/schema.type';
export type { Document } from './types/document';
export type { ErrorType } from './utils/error/errorTypes';