import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the root of the docs folder
    }, 
    
  ],
};

export default sidebars;
