
const enum ErrorType {
	AbiMongoError = "AbiMongoError",
	AbiMongoErrorType = "AbiMongoErrorType",
	AbiMongoErrorStack = "AbiMongoErrorStack",
	AbiMongoErrorMessage = "AbiMongoErrorMessage",
	AbiMongoErrorCause = "AbiMongoErrorCause",
	AbiMongoCollectionError = "CollectionError",
	// AbiMongoConnectionError = "ConnectionError",
	AbimongoParseError = "ParseError",
	AbimongoBulkWriteError = "MongoBulkWriteError",
	AbiMongoConnectionError = "ConnectionError",
	AbiMongoSchemaError = "SchemaError",
	AbiMongoModelError = "ModelError",
	INITIALIZATION_ERROR = "INITIALIZATION_ERROR",
	ABIMONGO_ERROR = "ABIMONGO_ERROR",
	NULL_OR_UNDEFINED = "NULL_OR_UNDEFINED",
	INVALID_SCHEME_ERROR = "INVALID_SCHEME_ERROR",
	CONNECTION_ERROR = "UnCaughtException:: This is a ParseError or ConnectionError. Please check the connection string.",
	UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
	SCHEMA_ERROR = "SCHEMA_ERROR",
	SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR",
	NOT_FOUND = "NOT_FOUND",
	NO_DATABASE_FOUND = "NO_DATABASE_FOUND",
	NOT_FOUND_IN_CACHE = "NOT_FOUND_IN_CACHE",
	VALIDATION_ERROR = "VALIDATION_ERROR",
	UNIQUE_CONSTRAINT_VIOLATION = "UNIQUE_CONSTRAINT_VIOLATION",
}

export { ErrorType };